data:
  config:
    url: jdbc:mysql://ece-9014.cqw83rhbcuaz.us-west-2.rds.amazonaws.com:3306/demo?autoReconnect=true && useSSL=false
    username: root
    password: 12345678
    driver: com.mysql.cj.jdbc.Driver
    maxpoolsize: 10